### PR TITLE
decimaltoocta decimal,factoral ,fibonacci,heap sort

### PR DESCRIPTION
**Pull request by prm1999**
decimaltoocta decimal,factoral ,fibonacci,heap sort

### CODE REVIEW

**Review by aravindvnair99 — COMMENTED** [review]
@prm1999 I've deleted your factorial and fibonacci file from this PR as it's already present in the repository. Please check existing files before submitting:

- [Folder for C](https://github.com/DSC-ASEB/Getting-started-with-Hacktoberfest/tree/master/C)
- [Fibonacci](https://github.com/DSC-ASEB/Getting-started-with-Hacktoberfest/blob/master/C/Fibonacci%20(Recursions).c)
- [Factorial](https://github.com/DSC-ASEB/Getting-started-with-Hacktoberfest/blob/master/C/Factorial%20(Recursions).c)

**Comment by prm1999** [comment]
> @prm1999 I've deleted your factorial and fibonacci file from this PR as it's already present in the repository. Please check existing files before submitting:
> 
> * [Folder for C](https://github.com/DSC-ASEB/Getting-started-with-Hacktoberfest/tree/master/C)
> * [Fibonacci](https://github.com/DSC-ASEB/Getting-started-with-Hacktoberfest/blob/master/C/Fibonacci%20(Recursions).c)
> * [Factorial](https://github.com/DSC-ASEB/Getting-started-with-Hacktoberfest/blob/master/C/Factorial%20(Recursions).c)

Remaining file at PR accept

**Review by aravindvnair99 — CHANGES_REQUESTED** [review]
@prm1999 Why use a complex stack for a simple task as this? All you have to do is this:

```c
#include <stdio.h>

void decimaltoOctal(int deciNum)
{
	int octalNum = 0, countval = 1;
	int dNo = deciNum;
	while (deciNum != 0) {
		int remainder = deciNum % 8;
		octalNum += remainder * countval;
		countval = countval * 10;
		deciNum /= 8;
	}
	printf("Octal of %d is %d.", dNo, octalNum);
}

int main()
{
	int n;
	printf("Enter the decimal number: ");
	scanf("%d", &n);
	decimaltoOctal(n);
	return 0;
}
```

**Comment by aravindvnair99** [comment]
@prm1999 Moving this PR to draft. Once you are done with your changes, you can mark as `Ready for review`.

**Comment by prm1999** [comment]
> @prm1999 Why use a complex stack for a simple task as this? All you have to do is this:
> 
> ```c
> #include <stdio.h>
> 
> void decimaltoOctal(int deciNum)
> {
> 	int octalNum = 0, countval = 1;
> 	int dNo = deciNum;
> 	while (deciNum != 0) {
> 		int remainder = deciNum % 8;
> 		octalNum += remainder * countval;
> 		countval = countval * 10;
> 		deciNum /= 8;
> 	}
> 	printf("Octal of %d is %d.", dNo, octalNum);
> }
> 
> int main()
> {
> 	int n;
> 	printf("Enter the decimal number: ");
> 	scanf("%d", &n);
> 	decimaltoOctal(n);
> 	return 0;
> }
> ```

Simple way are  available every where but using stack is rare.

**Review by aravindvnair99 — CHANGES_REQUESTED** [review]
@prm1999 Your code doesn't show correct output for negative numbers though. Moving this PR to draft. Once you are done with your changes, you can mark as `Ready for review`.

**Comment by aravindvnair99** [comment]
> > @prm1999 Why use a complex stack for a simple task as this? All you have to do is this:
> > ```c
> > #include <stdio.h>
> > 
> > void decimaltoOctal(int deciNum)
> > {
> > 	int octalNum = 0, countval = 1;
> > 	int dNo = deciNum;
> > 	while (deciNum != 0) {
> > 		int remainder = deciNum % 8;
> > 		octalNum += remainder * countval;
> > 		countval = countval * 10;
> > 		deciNum /= 8;
> > 	}
> > 	printf("Octal of %d is %d.", dNo, octalNum);
> > }
> > 
> > int main()
> > {
> > 	int n;
> > 	printf("Enter the decimal number: ");
> > 	scanf("%d", &n);
> > 	decimaltoOctal(n);
> > 	return 0;
> > }
> > ```
> 
> Simple way are available every where but using stack is rare.

@prm1999 I'll consider your PR this time. But no one would implement such a conversion using stack in real life. That's unnecessary complexity and extra CPU load. When coding, you need to keep things optimised. Once you are done with your changes, you can mark as `Ready for review` and I'll review again.

**Comment by aravindvnair99** [comment]
@prm1999 Reminder: Your code for `Decimal to Octal` doesn't show correct output for negative numbers. If you fix that, I will merge this pull request. On the other hand, inactivity will lead to the pull request being closed without merging.

**Review by aravindvnair99 — CHANGES_REQUESTED** [review]
@prm1999 Saw your screenshot. But you did for a positive number. Check for a negative number. It gives the wrong output.

**Comment by prm1999** [comment]
> @prm1999 Saw your screenshot. But you did for a positive number. Check for a negative number. It gives the wrong outputs
Ok

**Comment by aravindvnair99** [comment]
> > @prm1999 Saw your screenshot. But you did for a positive number. Check for a negative number. It gives the wrong outputs
>
>Ok

@prm1999 Once you have fixed the output of negative numbers, you can mark as `Ready for review` and I'll merge the pull request if everything is fine after a review. Also, delete the 2 screenshots as that's not required.

**Comment by aravindvnair99** [comment]
@prm1999 5 more days to go. Inactivity will lead to the pull request being closed.

**Comment by prm1999** [comment]
check and merge PR

**Review by aravindvnair99 — CHANGES_REQUESTED** [review]
@prm1999 Please delete `Screenshot (25).png` and `Screenshot (26).png`

**Review by aravindvnair99 — CHANGES_REQUESTED** [review]
@prm1999 Please make the following corrections by today to be eligible for merging:

- `C/Decimal to Hexadecimal using stack.c`  and `C/Decimal to Octal using Stack.c` doesn't work for negative decimal number. You can either correct the code or delete the file as I can't merge not working code.
- Please delete `Screenshot (25).png` and `Screenshot (26).png` as that's not required.

**Comment by aravindvnair99** [comment]
@prm1999 Moving this PR to draft. Once you are done with your changes, you can mark as `Ready for review`.

**Comment by aravindvnair99** [comment]
@prm1999 One more day to go for Hacktoberfest to end. Inactivity will lead to the pull request being closed without merging.

**Review by aravindvnair99 — APPROVED** [review]
@prm1999 Deleted the incorrect files containing wrong code. Will merge the rest.

**Pull request merged**
