### PR TITLE
DiamondPattern.java

### PR DESCRIPTION
**Pull request by Raghav-Bajaj**
This will create Diamond pattern.

### CODE REVIEW

**Review by aravindvnair99 — CHANGES_REQUESTED** [review]
@Raghav-Bajaj Nice work, two points:

- Could you also add code to prevent it from crashing when a non-integer number is received? Instead, ask the user to renter the input.
- When entering an odd number, it's proper. But even numbers don't give a perfect diamond. Ends up with `***` at the end.

Could you fix these two?

**Comment by aravindvnair99** [comment]
@Raghav-Bajaj Moving this PR to draft. Once you are done with your changes, you can mark as `Ready for review`.

**Review by Raghav-Bajaj — COMMENTED** [review]
all required changes have been made

**Review by aravindvnair99 — DISMISSED** [review]

**Review by aravindvnair99 — APPROVED** [review]

**Comment by aravindvnair99** [comment]
> all required changes have been made

@Raghav-Bajaj That wasn't the right way to do it. Anyways, I've fixed your code. Have a look at https://github.com/DSC-ASEB/Getting-started-with-Hacktoberfest/pull/15/commits/1bb58d8afd89d45b4e68229ab39f9d18e2ed6d80 for what I did. Merging now. Thanks for your contribution!

You can go to https://bit.ly/DSC-ASEB-Events to be a part of other events.

<blockquote><div><strong><a href="https://dsc.community.dev/amrita-school-of-engineering-bengaluru/">Amrita School of Engineering, Bengaluru | Developer Student Clubs</a></strong></div><div>Check out Developer Student Clubs Amrita School of Engineering, Bengaluru events, learn more or contact this organizer.</div></blockquote>

**Pull request merged**
