### PR TITLE
Added Rainfall prediction using linear regression

### LINKED ISSUE #9: can i create a new pull request?
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by Ashlin21dev**
This is the same PR of a code which i contributed a while ago ,but i have rectified the errors and added a proper description.

### CODE REVIEW

**Comment by Ashlin21dev** [comment]
can you please review it sir @aravindvnair99 ?

**Review by aravindvnair99 — CHANGES_REQUESTED** [review]
@Ashlin21dev Include `austin_weather.csv` also. The file is missing. Also, I recommend trying to code on your own than copy-pasting from [here](https://www.geeksforgeeks.org/ml-rainfall-prediction-using-linear-regression/).

**Comment by aravindvnair99** [comment]
@Ashlin21dev Moving this PR to draft. Once you are done with your changes, you can mark as `Ready for review`.

**Comment by aravindvnair99** [comment]
@Ashlin21dev Reminder: If you fix the pending issues stated above, I will merge this pull request. On the other hand, inactivity will lead to the pull request being closed without merging.

**Comment by Ashlin21dev** [comment]
> @Ashlin21dev Reminder: If you fix the pending issues stated above, I will merge this pull request. On the other hand, inactivity will lead to the pull request being closed without merging.

will do it11

**Comment by aravindvnair99** [comment]
@Ashlin21dev 5 more days to go. Inactivity will lead to the pull request being closed.

**Comment by aravindvnair99** [comment]
@Ashlin21dev Closing this PR due to inactivity. Feel free to resend after making necessary changes.

**Pull request closed without merging**
