### PR TITLE
added my first pull request,please accept it

### LINKED ISSUE #9: can i create a new pull request?
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by Ashlin21dev**

### CODE REVIEW

**Review by aravindvnair99 — CHANGES_REQUESTED** [review]
@Ashlin21dev You have put the extension as `json`. Did you mean `py`?

**Comment by Ashlin21dev** [comment]
@aravindvnair99 i will change that sir!!

**Comment by Ashlin21dev** [comment]
so shall I make a new pull request?

**Comment by aravindvnair99** [comment]
> so shall I make a new pull request?

@Ashlin21dev You can edit in the same PR itself. But up to you. Also, one more thing, @BhuvanashreeM has already added a file for bubble sort [here](https://github.com/DSC-ASEB/Getting-started-with-Hacktoberfest/blob/master/Python/bubble_sort.py). So send in something else which doesn't currently exist in the repository. If you are interested in Python, check [this](https://github.com/DSC-ASEB/Getting-started-with-Hacktoberfest/tree/master/Python) folder.

**Pull request closed without merging**
