### PR TITLE
added a snake game

### LINKED ISSUE #9: can i create a new pull request?
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by Ashlin21dev**
its my first decent try to do a pull request with a useful code, I hope it gets accepted!!(Hacktoberfest-2020)

### CODE REVIEW

**Review by aravindvnair99 — CHANGES_REQUESTED** [review]
@Ashlin21dev, the game doesn't work as it should. When the snake bumps into itself, it doesn't die. Also, when it crashes the boundary, it doesn't die either. You can try fixing that.

In addition to that, I would suggest trying to type something on your own than copy-pasting from the internet. Because you will learn Python, Git and GitHub that refer. Have a look at the resources I shared with you here: https://github.com/DSC-ASEB/Getting-started-with-Hacktoberfest/issues/9#issuecomment-711144162

**Comment by Ashlin21dev** [comment]
sure i will do that and and i also want a plus one in the hacktober fest, really sorry if if broke some rule.

**Comment by Ashlin21dev** [comment]
i wish if it gets approved by you!!

**Comment by aravindvnair99** [comment]
@Ashlin21dev Moving this PR to draft. Once you are done with your changes, you can mark as `Ready for review`.

**Comment by aravindvnair99** [comment]
@Ashlin21dev Reminder: If you fix the pending issues stated above, I will merge this pull request. On the other hand, inactivity will lead to the pull request being closed without merging.

**Comment by Ashlin21dev** [comment]
> @Ashlin21dev Reminder: If you fix the pending issues stated above, I will merge this pull request. On the other hand, inactivity will lead to the pull request being closed without merging.

on it!!

**Comment by aravindvnair99** [comment]
> > @Ashlin21dev Reminder: If you fix the pending issues stated above, I will merge this pull request. On the other hand, inactivity will lead to the pull request being closed without merging.
> 
> on it!!

@Ashlin21dev Moving this PR to draft. Once you are done with your changes, you can mark as `Ready for review`.

**Comment by aravindvnair99** [comment]
@Ashlin21dev Closing this PR due to inactivity. Feel free to resend after making necessary changes.

**Pull request closed without merging**
